controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_fruits:
    path: /fruits/all
    controller: App\Controller\FruitController::all
